/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppointmentAutomation;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ExtractAppointmentInformations extends javax.swing.JFrame {

    private AppointmentInformations info;
    private String text;

    public ExtractAppointmentInformations() {
        initComponents();
    }

    public ExtractAppointmentInformations(AppointmentInformations info) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.info = info;
        this.setTitle("Appointment Informations Extract");

        this.lbl_appointmentDay.setText(info.getAppointmentDate());
        this.lbl_appointmentTime.setText(info.getAppointmentTime());
        this.lbl_doctorName.setText(info.getDoctorName());
        this.lbl_doctorSurname.setText(info.getDoctorSurname());
        this.lbl_patientIdentificationNumber.setText(info.getIdentificationNumber());
        this.lbl_patientName.setText(info.getPatientName());
        this.lbl_patientSurname.setText(info.getPatientSurname());
        this.lbl_department.setText(info.getDoctorDepartment());
        this.txta_complaint.setText(info.getComplaint());

        text = "Patient information\n"
                + "---------------------------\n"
                + "Name: " + info.getPatientName() + "\n"
                + "Surname: " + info.getPatientSurname() + "\n"
                + "Identification Number: " + info.getIdentificationNumber() + "\n"
                + "----------------------------\n"
                + "Doctor information\n"
                + "----------------------------\n"
                + "Name: " + info.getDoctorName() + "\n"
                + "Surname: " + info.getDoctorSurname() + "\n"
                + "Department: " + info.getDoctorDepartment() + "\n"
                + "----------------------------\n"
                + "Appointment Information\n"
                + "----------------------------\n"
                + "Appointment date:" + info.getAppointmentDate() + "\n"
                + "Appointment time:" + info.getAppointmentTime() + "\n"
                + "Complaint : " + info.getComplaint();

        this.txta_informations.setText(text);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_patient = new javax.swing.JPanel();
        lbl_patientNameTag = new javax.swing.JLabel();
        lbl_patientSurnameTag = new javax.swing.JLabel();
        lbl_patientIdentificationNumberTag = new javax.swing.JLabel();
        lbl_patientName = new javax.swing.JLabel();
        lbl_patientSurname = new javax.swing.JLabel();
        lbl_patientIdentificationNumber = new javax.swing.JLabel();
        pnl_doctor = new javax.swing.JPanel();
        lbl_doctorNameTag = new javax.swing.JLabel();
        lbl_doctorSurnameTag = new javax.swing.JLabel();
        lbl_doctorName = new javax.swing.JLabel();
        lbl_doctorSurname = new javax.swing.JLabel();
        lbl_departmentTag = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        pnl_appointmentDate = new javax.swing.JPanel();
        lbl_appointmentDayTag = new javax.swing.JLabel();
        lbl_appointmentTimeTag = new javax.swing.JLabel();
        lbl_appointmentDay = new javax.swing.JLabel();
        lbl_appointmentTime = new javax.swing.JLabel();
        pnl_complaint5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_complaint = new javax.swing.JTextArea();
        btn_extract = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txta_informations = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        pnl_patient.setBackground(new java.awt.Color(51, 255, 255));
        pnl_patient.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient"));

        lbl_patientNameTag.setText("Name:");

        lbl_patientSurnameTag.setText("Surname:");

        lbl_patientIdentificationNumberTag.setText("Identification Number:");

        javax.swing.GroupLayout pnl_patientLayout = new javax.swing.GroupLayout(pnl_patient);
        pnl_patient.setLayout(pnl_patientLayout);
        pnl_patientLayout.setHorizontalGroup(
            pnl_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_patientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_patientLayout.createSequentialGroup()
                        .addComponent(lbl_patientNameTag)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_patientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_patientLayout.createSequentialGroup()
                        .addComponent(lbl_patientSurnameTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_patientSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_patientLayout.createSequentialGroup()
                        .addComponent(lbl_patientIdentificationNumberTag)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_patientIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_patientLayout.setVerticalGroup(
            pnl_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_patientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_patientNameTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_patientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_patientSurnameTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_patientSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_patientIdentificationNumberTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_patientIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pnl_doctor.setBackground(new java.awt.Color(153, 153, 255));
        pnl_doctor.setBorder(javax.swing.BorderFactory.createTitledBorder("Doctor"));

        lbl_doctorNameTag.setText("Name:");

        lbl_doctorSurnameTag.setText("Surname:");

        lbl_departmentTag.setText("Department:");

        javax.swing.GroupLayout pnl_doctorLayout = new javax.swing.GroupLayout(pnl_doctor);
        pnl_doctor.setLayout(pnl_doctorLayout);
        pnl_doctorLayout.setHorizontalGroup(
            pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_doctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_doctorSurnameTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_departmentTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_doctorNameTag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_doctorLayout.createSequentialGroup()
                        .addComponent(lbl_department, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_doctorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_doctorSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_doctorLayout.setVerticalGroup(
            pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_doctorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_doctorNameTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_doctorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_doctorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_doctorSurnameTag))
                    .addComponent(lbl_doctorSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(pnl_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_departmentTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_appointmentDate.setBackground(new java.awt.Color(0, 204, 51));
        pnl_appointmentDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Appointment Date"));

        lbl_appointmentDayTag.setText("Appointment Day:");

        lbl_appointmentTimeTag.setText("Time:");

        javax.swing.GroupLayout pnl_appointmentDateLayout = new javax.swing.GroupLayout(pnl_appointmentDate);
        pnl_appointmentDate.setLayout(pnl_appointmentDateLayout);
        pnl_appointmentDateLayout.setHorizontalGroup(
            pnl_appointmentDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_appointmentDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_appointmentDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_appointmentDateLayout.createSequentialGroup()
                        .addComponent(lbl_appointmentDayTag, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_appointmentDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_appointmentDateLayout.createSequentialGroup()
                        .addComponent(lbl_appointmentTimeTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_appointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_appointmentDateLayout.setVerticalGroup(
            pnl_appointmentDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_appointmentDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_appointmentDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_appointmentDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_appointmentDayTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnl_appointmentDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_appointmentTimeTag, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_appointmentTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pnl_complaint5.setBackground(new java.awt.Color(0, 204, 51));
        pnl_complaint5.setBorder(javax.swing.BorderFactory.createTitledBorder("Complaint"));

        txta_complaint.setEditable(false);
        txta_complaint.setBackground(new java.awt.Color(0, 204, 153));
        txta_complaint.setColumns(20);
        txta_complaint.setRows(5);
        jScrollPane1.setViewportView(txta_complaint);

        javax.swing.GroupLayout pnl_complaint5Layout = new javax.swing.GroupLayout(pnl_complaint5);
        pnl_complaint5.setLayout(pnl_complaint5Layout);
        pnl_complaint5Layout.setHorizontalGroup(
            pnl_complaint5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_complaint5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_complaint5Layout.setVerticalGroup(
            pnl_complaint5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_complaint5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_extract.setText("Extract");
        btn_extract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_extractActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Extract"));

        txta_informations.setEditable(false);
        txta_informations.setBackground(new java.awt.Color(0, 153, 153));
        txta_informations.setColumns(20);
        txta_informations.setRows(5);
        jScrollPane7.setViewportView(txta_informations);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_extract, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnl_appointmentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnl_complaint5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnl_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_appointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnl_complaint5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_extract)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_extractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_extractActionPerformed
        try {
            txta_informations.print();
        } catch (PrinterException ex) {
            Logger.getLogger(ExtractAppointmentInformations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_extractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtractAppointmentInformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtractAppointmentInformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtractAppointmentInformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtractAppointmentInformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtractAppointmentInformations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_extract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbl_appointmentDay;
    private javax.swing.JLabel lbl_appointmentDayTag;
    private javax.swing.JLabel lbl_appointmentTime;
    private javax.swing.JLabel lbl_appointmentTimeTag;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_departmentTag;
    private javax.swing.JLabel lbl_doctorName;
    private javax.swing.JLabel lbl_doctorNameTag;
    private javax.swing.JLabel lbl_doctorSurname;
    private javax.swing.JLabel lbl_doctorSurnameTag;
    private javax.swing.JLabel lbl_patientIdentificationNumber;
    private javax.swing.JLabel lbl_patientIdentificationNumberTag;
    private javax.swing.JLabel lbl_patientName;
    private javax.swing.JLabel lbl_patientNameTag;
    private javax.swing.JLabel lbl_patientSurname;
    private javax.swing.JLabel lbl_patientSurnameTag;
    private javax.swing.JPanel pnl_appointmentDate;
    private javax.swing.JPanel pnl_complaint5;
    private javax.swing.JPanel pnl_doctor;
    private javax.swing.JPanel pnl_patient;
    private javax.swing.JTextArea txta_complaint;
    private javax.swing.JTextArea txta_informations;
    // End of variables declaration//GEN-END:variables
}
