package AppointmentAutomation;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bilal
 */
public class Register extends javax.swing.JFrame {

    private LogIn loginScreen;

    private String username;
    private String password;
    private String identificationNumber;
    private String phoneNumber;
    private String personalName;
    private String surname;
    private String email;
    private String birthday;
    private String weight;
    private String height;
    private String department;
    private String gender;
    private String userType;
    private String id;

    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);

        int securityNumber = (int) (Math.random() * 9999);
        this.lbl_securityNumberInt.setText(Integer.toString(securityNumber));//security number is prepared for confirmation

        this.rbtn_worker.setSelected(true);
    }

    public Register(LogIn loginScreen) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.loginScreen = loginScreen;

        int securityNumber = (int) (Math.random() * 9999);
        this.lbl_securityNumberInt.setText(Integer.toString(securityNumber));//security number is prepared for confirmation

        this.rbtn_worker.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_usertyoe = new javax.swing.ButtonGroup();
        btngrp_gender = new javax.swing.ButtonGroup();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_phoneNumber = new javax.swing.JLabel();
        ftxt_phoneNumber = new javax.swing.JFormattedTextField();
        lbl_identificationNumber = new javax.swing.JLabel();
        txt_identicationNumber = new javax.swing.JTextField();
        txt_securityNumber = new javax.swing.JTextField();
        lbl_securityNumber = new javax.swing.JLabel();
        pnl_securityNumber = new javax.swing.JPanel();
        lbl_securityNumberInt = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_surname = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_userType = new javax.swing.JLabel();
        rbtn_worker = new javax.swing.JRadioButton();
        rbtn_patient = new javax.swing.JRadioButton();
        lbl_gender = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        lbl_weight = new javax.swing.JLabel();
        spnr_weight = new javax.swing.JSpinner();
        lbl_height1 = new javax.swing.JLabel();
        spnr_height = new javax.swing.JSpinner();
        lbl_department = new javax.swing.JLabel();
        cmbx_department = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_registerText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_day = new javax.swing.JLabel();
        lbl_month = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        spnr_day = new javax.swing.JSpinner();
        spnr_month = new javax.swing.JSpinner();
        spnr_year = new javax.swing.JSpinner();
        lbl_workerType = new javax.swing.JLabel();
        cmbx_workerType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_username.setText("Username :");

        lbl_password.setText("Password :");

        lbl_phoneNumber.setText("Phone Number :");

        try {
            ftxt_phoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+90 (###) ###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbl_identificationNumber.setText("Identification Number:");

        lbl_securityNumber.setText("Security Number:");

        pnl_securityNumber.setBackground(new java.awt.Color(0, 0, 0));

        lbl_securityNumberInt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_securityNumberInt.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnl_securityNumberLayout = new javax.swing.GroupLayout(pnl_securityNumber);
        pnl_securityNumber.setLayout(pnl_securityNumberLayout);
        pnl_securityNumberLayout.setHorizontalGroup(
            pnl_securityNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_securityNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_securityNumberInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_securityNumberLayout.setVerticalGroup(
            pnl_securityNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_securityNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_securityNumberInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_name.setText("Name:");

        lbl_surname.setText("Surname:");

        lbl_email.setText("E-mail");

        lbl_userType.setText("UserType:");

        btngrp_usertyoe.add(rbtn_worker);
        rbtn_worker.setText("Worker");
        rbtn_worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_workerActionPerformed(evt);
            }
        });

        btngrp_usertyoe.add(rbtn_patient);
        rbtn_patient.setText("Patient");
        rbtn_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_patientActionPerformed(evt);
            }
        });

        lbl_gender.setText("Gender:");

        btngrp_gender.add(rbtn_male);
        rbtn_male.setText("Male");

        btngrp_gender.add(rbtn_female);
        rbtn_female.setText("Female");

        lbl_weight.setText("Weight:");

        spnr_weight.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));
        spnr_weight.setMinimumSize(new java.awt.Dimension(54, 25));
        spnr_weight.setPreferredSize(new java.awt.Dimension(54, 25));

        lbl_height1.setText("Height:");

        spnr_height.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));
        spnr_height.setMinimumSize(new java.awt.Dimension(54, 25));
        spnr_height.setPreferredSize(new java.awt.Dimension(54, 25));

        lbl_department.setText("Department:");

        cmbx_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Ear Nose and Throat", "Gastroenterology", "General Surgery", "Neurology", "Psychology", " " }));

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.setToolTipText("");

        lbl_registerText.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_registerText.setForeground(new java.awt.Color(204, 0, 0));
        lbl_registerText.setText("REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(lbl_registerText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_registerText, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Birthday"));
        jPanel3.setMinimumSize(new java.awt.Dimension(179, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(179, 140));

        lbl_day.setText("Day:");

        lbl_month.setText("Month:");

        lbl_year.setText("Year:");

        spnr_day.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spnr_month.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnr_year.setModel(new javax.swing.SpinnerNumberModel(1850, 1850, 2100, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_day)
                        .addGap(32, 32, 32)
                        .addComponent(spnr_day, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_month)
                            .addComponent(lbl_year))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnr_month)
                            .addComponent(spnr_year, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnr_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_day))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_month)
                    .addComponent(spnr_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_year)
                    .addComponent(spnr_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        lbl_workerType.setText("Worker Type:");

        cmbx_workerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "IT", "Secretary", "Administrator" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addComponent(lbl_weight)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnr_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_height1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnr_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_securityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_securityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(pnl_securityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_identificationNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_identicationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_department)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(cmbx_department, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_surname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_phoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_username)
                                                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(26, 26, 26)))
                                    .addComponent(lbl_name))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftxt_phoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txt_username)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_userType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtn_patient)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addComponent(rbtn_worker))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_gender)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtn_male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtn_female))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_workerType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbx_workerType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_worker)
                    .addComponent(lbl_userType)
                    .addComponent(rbtn_patient))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password)
                    .addComponent(lbl_gender)
                    .addComponent(rbtn_male)
                    .addComponent(rbtn_female))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_phoneNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_name)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_surname)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnr_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_weight)
                        .addComponent(spnr_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_height1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_email)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_department)
                    .addComponent(lbl_workerType)
                    .addComponent(cmbx_workerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_identicationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_identificationNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_securityNumber)
                                .addGap(18, 18, 18)
                                .addComponent(txt_securityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .addComponent(pnl_securityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        //user can pass to login screen when perform exit button.
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure to leave this section?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmation == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            loginScreen.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "You can continue to save your account");
        }
    }//GEN-LAST:event_btn_exitActionPerformed


    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        //Following, inputs which user enter is controlled.
        String securityNumber = txt_securityNumber.getText();
        if (!securityNumber.equals(this.lbl_securityNumberInt.getText())) {//Security number is controlled.
            JOptionPane.showMessageDialog(this, "The security number is wrong. Please enter the input again.");
            return;
        }
        //password is created and controlled.
        char[] passwordArr = txt_password.getPassword();
        String password = "";
        for (char ch : passwordArr) {
            password += ch;
        }

        if (!rbtn_female.isSelected() && !rbtn_male.isSelected()) {//to create a new user,Components are controlled whether they are selected or not 
            JOptionPane.showMessageDialog(this, "Please be sure to select gender");
            return;
        }
        if (!rbtn_patient.isSelected() && !rbtn_worker.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please be sure to select user type");
            return;
        }
        if (!ftxt_phoneNumber.isEditValid()) {
            JOptionPane.showMessageDialog(this, "Please be sure to fill telephone number");
            return;
        }

        //Regular Expression section. All of input are controlled by certain pattern and are controlled whether they are empty or not. 
        String pattern = "";
        String warning = "";

        pattern = "^[a-zA-Z0-9]{3,}$";//username control
        warning = "Please, enter at least 3 letter for username";
        if (!this.loginScreen.inputContentControl(pattern, txt_username.getText(), warning)) {
            return;
        }
        pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z0-9]{5,}$";//password control
        warning = "Please, for password, enter at least 5 letter and enter at least 1 uppercase,1 lowercase and 1 digit.";
        if (!this.loginScreen.inputContentControl(pattern, password, warning)) {
            return;
        }
        pattern = "^\\d{11}$";//identification number control
        warning = "Please, enter 11 digit to identification number";
        if (!this.loginScreen.inputContentControl(pattern, txt_identicationNumber.getText(), warning)) {
            return;
        }
        pattern = "^[\\w]{3,}(\\s\\w{3,})*$";//name control. User can have 1 or more name,surname.
        warning = "Please, enter at least 3 word for name and surname";
        if (!this.loginScreen.inputContentControl(pattern, txt_name.getText(), warning) || !this.loginScreen.inputContentControl(pattern, txt_surname.getText(), warning)) {
            return;
        }
        pattern = "^[a-zA-Z][\\w\\d]{2,}@(gmail|hotmail)(\\.com)$";//e-mail control.
        warning = "Please, enter at least 3 word and use gmail or hotmail ";
        if (!this.loginScreen.inputContentControl(pattern, txt_email.getText(), warning)) {
            return;
        }
        //User inputs is created
        String day = "0";
        String month = "0";
        String controlBirthday = "" + ((int) spnr_day.getValue());//Birthday date is created starting with 0 if number is just a digit
        if (controlBirthday.length() == 1) {
            day += controlBirthday;
        } else {
            day = controlBirthday;
        }
        controlBirthday = "" + ((int) spnr_month.getValue());//Birthday date is created starting with 0 if number is just a digit
        if (controlBirthday.length() == 1) {
            month += controlBirthday;
        } else {
            month = controlBirthday;
        }

        //Inpurts are assigned to the class variables.
        this.username = txt_username.getText();
        this.password = password;
        this.identificationNumber = txt_identicationNumber.getText();
        this.phoneNumber = ftxt_phoneNumber.getText();
        this.personalName = txt_name.getText();
        this.surname = txt_surname.getText();
        this.email = txt_email.getText();
        this.birthday = day + "/" + month + "/" + ((int) spnr_year.getValue());
        this.weight = "" + ((int) spnr_weight.getValue());
        this.height = "" + ((int) spnr_height.getValue());
        if (rbtn_female.isSelected()) {
            this.gender = "Female";
        } else {
            this.gender = "Male";
        }
        if (rbtn_patient.isSelected()) {
            this.userType = "Standart user";
            this.department = "-";
        } else {
            this.userType = (String) cmbx_workerType.getSelectedItem();
            if (userType.equals("Doctor")) {
                this.department = (String) cmbx_department.getSelectedItem();
            } else {
                this.department = "-";
            }
        }
        //Inputs insert into database
        insertInformation();
        //Login screen is executed
        this.setVisible(false);
        loginScreen.setVisible(true);
    }//GEN-LAST:event_btn_saveActionPerformed
    public void insertInformation() {

        //Following, database is transmitted and the inputs are compored with database information.
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/AppoinmentProgram", "sa", "as");
            //biggest id is taken.
            String query2 = "SELECT MAX (ID) FROM TBL_USERS";
            Statement stmt = conn.createStatement();
            ResultSet rst = stmt.executeQuery(query2);
            rst.next();
            this.id = Integer.toString(1 + rst.getInt(1));

            //The inputs are inserted following
            String query = "INSERT INTO TBL_USERS VALUES("
                    + id
                    + ",'" + this.identificationNumber + "'"
                    + ",'" + this.personalName + "'"
                    + ",'" + this.surname + "'"
                    + ",'" + this.email + "'"
                    + ",'" + this.gender + "'"
                    + ",'" + this.birthday + "'"
                    + "," + Double.valueOf(this.weight) + ""
                    + "," + Double.valueOf(this.height) + ""
                    + ",'" + this.userType + "'"
                    + ",'" + this.department + "'"
                    + ",'" + this.phoneNumber + "'"
                    + ",'" + this.username + "'"
                    + ",'" + this.password + "')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "The account is created. You can log in from first screen.");
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void rbtn_workerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_workerActionPerformed
        cmbx_department.setEnabled(true);
        cmbx_workerType.setEnabled(true);

    }//GEN-LAST:event_rbtn_workerActionPerformed

    private void rbtn_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_patientActionPerformed
        cmbx_department.setEnabled(false);
        cmbx_workerType.setEnabled(false);     }//GEN-LAST:event_rbtn_patientActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup btngrp_gender;
    private javax.swing.ButtonGroup btngrp_usertyoe;
    private javax.swing.JComboBox<String> cmbx_department;
    private javax.swing.JComboBox<String> cmbx_workerType;
    private javax.swing.JFormattedTextField ftxt_phoneNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_height1;
    private javax.swing.JLabel lbl_identificationNumber;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_registerText;
    private javax.swing.JLabel lbl_securityNumber;
    private javax.swing.JLabel lbl_securityNumberInt;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_weight;
    private javax.swing.JLabel lbl_workerType;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JPanel pnl_securityNumber;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JRadioButton rbtn_patient;
    private javax.swing.JRadioButton rbtn_worker;
    private javax.swing.JSpinner spnr_day;
    private javax.swing.JSpinner spnr_height;
    private javax.swing.JSpinner spnr_month;
    private javax.swing.JSpinner spnr_weight;
    private javax.swing.JSpinner spnr_year;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_identicationNumber;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_securityNumber;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
